# Generated by Django 6.0.4 on 2026-05-19 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(blank=True, default='', max_length=255)),
                ('isbn', models.CharField(blank=True, default='', max_length=50)),
                ('edition', models.CharField(blank=True, default='', max_length=50)),
                ('year_published', models.CharField(blank=True, default='', max_length=10)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('course_code', models.CharField(blank=True, default='', max_length=50)),
                ('shelf_location', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('available', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('language', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('librarian', 'Librarian')], default='student', max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photo/')),
                ('enrollment', models.CharField(max_length=60)),
                ('admission_year', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('librarian_id', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
