# Generated by Django 6.0.4 on 2026-05-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('librarian', 'Librarian')], default='student', max_length=20),
        ),
    ]
