# Generated by Django 6.0.4 on 2026-05-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='librarian_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
